name: Publish Image

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: wxx9248/tftpd

permissions:
  packages: write

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checking Out Repository
      uses: actions/checkout@v3

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.7.0

    - name: Log in to the Container Registry
      uses: docker/login-action@v2.2.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4.6.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
