name: Pull Request Check

on:
  pull_request:
    branches: 
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checking Out Repository
      uses: actions/checkout@v3

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.7.0

    - name: Build the Docker Image
      run: docker buildx build .
